
wcat: wcat.c
	gcc -o wcat wcat.c -Wall -Werror

wgrep: wgrep.c
	gcc -g -o wgrep wgrep.c -Wall -Werror

wzip: wzip.c
	gcc -g -o wzip wzip.c -Wall -Werror

wunzip: wunzip.c
	gcc -g -o wunzip wunzip.c -Wall -Werror

clean:
	rm -f wgrep wcat wzip wunzip
